/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as CambiarContrasenaRouteImport } from './routes/cambiar-contrasena'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccesoDenegadoRouteImport } from './routes/_app/acceso-denegado'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppCuentaRouteImport } from './routes/_app/cuenta'
import { Route as AppFacturasRouteImport } from './routes/_app/facturas'
import { Route as AppClientesClienteIdRouteImport } from './routes/_app/clientes/$clienteId'
import { Route as AppClientesNuevoRouteImport } from './routes/_app/clientes/nuevo'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app/configuracion/index'
import { Route as AppConfiguracionAuditoriaRouteImport } from './routes/_app/configuracion/auditoria'
import { Route as AppConfiguracionFacturacionRouteImport } from './routes/_app/configuracion/facturacion'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app/configuracion/usuarios'
import { Route as AppFacturasNuevaRouteImport } from './routes/_app/facturas/nueva'
import { Route as AppFacturasFacturaIdIndexRouteImport } from './routes/_app/facturas/$facturaId/index'
import { Route as AppFacturasFacturaIdModificarRouteImport } from './routes/_app/facturas/$facturaId/modificar'
import { Route as AppFacturasBorradoresBorradorIdRouteImport } from './routes/_app/facturas/borradores/$borradorId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarContrasenaRoute = CambiarContrasenaRouteImport.update({
  id: '/cambiar-contrasena',
  path: '/cambiar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccesoDenegadoRoute = AppAccesoDenegadoRouteImport.update({
  id: '/acceso-denegado',
  path: '/acceso-denegado',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturasRoute = AppFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesNuevoRoute = AppClientesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppConfiguracionAuditoriaRoute =
  AppConfiguracionAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionFacturacionRoute =
  AppConfiguracionFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppFacturasNuevaRoute = AppFacturasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppFacturasRoute,
} as any)
const AppFacturasFacturaIdIndexRoute =
  AppFacturasFacturaIdIndexRouteImport.update({
    id: '/$facturaId/',
    path: '/$facturaId/',
    getParentRoute: () => AppFacturasRoute,
  } as any)
const AppFacturasFacturaIdModificarRoute =
  AppFacturasFacturaIdModificarRouteImport.update({
    id: '/$facturaId/modificar',
    path: '/$facturaId/modificar',
    getParentRoute: () => AppFacturasRoute,
  } as any)
const AppFacturasBorradoresBorradorIdRoute =
  AppFacturasBorradoresBorradorIdRouteImport.update({
    id: '/borradores/$borradorId',
    path: '/borradores/$borradorId',
    getParentRoute: () => AppFacturasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracion': typeof AppConfiguracionRouteWithChildren
  '/cuenta': typeof AppCuentaRoute
  '/facturas': typeof AppFacturasRouteWithChildren
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/configuracion/facturacion': typeof AppConfiguracionFacturacionRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/facturas/nueva': typeof AppFacturasNuevaRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
  '/facturas/$facturaId/modificar': typeof AppFacturasFacturaIdModificarRoute
  '/facturas/borradores/$borradorId': typeof AppFacturasBorradoresBorradorIdRoute
  '/facturas/$facturaId/': typeof AppFacturasFacturaIdIndexRoute
}
export interface FileRoutesByTo {
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/cuenta': typeof AppCuentaRoute
  '/facturas': typeof AppFacturasRouteWithChildren
  '/': typeof AppIndexRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/configuracion/facturacion': typeof AppConfiguracionFacturacionRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/facturas/nueva': typeof AppFacturasNuevaRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
  '/facturas/$facturaId/modificar': typeof AppFacturasFacturaIdModificarRoute
  '/facturas/borradores/$borradorId': typeof AppFacturasBorradoresBorradorIdRoute
  '/facturas/$facturaId': typeof AppFacturasFacturaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/_app/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/_app/cuenta': typeof AppCuentaRoute
  '/_app/facturas': typeof AppFacturasRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/_app/clientes/nuevo': typeof AppClientesNuevoRoute
  '/_app/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/_app/configuracion/facturacion': typeof AppConfiguracionFacturacionRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/_app/facturas/nueva': typeof AppFacturasNuevaRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
  '/_app/facturas/$facturaId/modificar': typeof AppFacturasFacturaIdModificarRoute
  '/_app/facturas/borradores/$borradorId': typeof AppFacturasBorradoresBorradorIdRoute
  '/_app/facturas/$facturaId/': typeof AppFacturasFacturaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/cambiar-contrasena'
    | '/acceso-denegado'
    | '/clientes'
    | '/configuracion'
    | '/cuenta'
    | '/facturas'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/configuracion/auditoria'
    | '/configuracion/facturacion'
    | '/configuracion/usuarios'
    | '/facturas/nueva'
    | '/configuracion/'
    | '/facturas/$facturaId/modificar'
    | '/facturas/borradores/$borradorId'
    | '/facturas/$facturaId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acceso'
    | '/cambiar-contrasena'
    | '/acceso-denegado'
    | '/clientes'
    | '/cuenta'
    | '/facturas'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/configuracion/auditoria'
    | '/configuracion/facturacion'
    | '/configuracion/usuarios'
    | '/facturas/nueva'
    | '/configuracion'
    | '/facturas/$facturaId/modificar'
    | '/facturas/borradores/$borradorId'
    | '/facturas/$facturaId'
  id:
    | '__root__'
    | '/_app'
    | '/acceso'
    | '/cambiar-contrasena'
    | '/_app/acceso-denegado'
    | '/_app/clientes'
    | '/_app/configuracion'
    | '/_app/cuenta'
    | '/_app/facturas'
    | '/_app/'
    | '/_app/clientes/$clienteId'
    | '/_app/clientes/nuevo'
    | '/_app/configuracion/auditoria'
    | '/_app/configuracion/facturacion'
    | '/_app/configuracion/usuarios'
    | '/_app/facturas/nueva'
    | '/_app/configuracion/'
    | '/_app/facturas/$facturaId/modificar'
    | '/_app/facturas/borradores/$borradorId'
    | '/_app/facturas/$facturaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  CambiarContrasenaRoute: typeof CambiarContrasenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-contrasena': {
      id: '/cambiar-contrasena'
      path: '/cambiar-contrasena'
      fullPath: '/cambiar-contrasena'
      preLoaderRoute: typeof CambiarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acceso-denegado': {
      id: '/_app/acceso-denegado'
      path: '/acceso-denegado'
      fullPath: '/acceso-denegado'
      preLoaderRoute: typeof AppAccesoDenegadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuenta': {
      id: '/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturas': {
      id: '/_app/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof AppFacturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$clienteId': {
      id: '/_app/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/nuevo': {
      id: '/_app/clientes/nuevo'
      path: '/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AppClientesNuevoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/auditoria': {
      id: '/_app/configuracion/auditoria'
      path: '/auditoria'
      fullPath: '/configuracion/auditoria'
      preLoaderRoute: typeof AppConfiguracionAuditoriaRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/facturacion': {
      id: '/_app/configuracion/facturacion'
      path: '/facturacion'
      fullPath: '/configuracion/facturacion'
      preLoaderRoute: typeof AppConfiguracionFacturacionRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/facturas/nueva': {
      id: '/_app/facturas/nueva'
      path: '/nueva'
      fullPath: '/facturas/nueva'
      preLoaderRoute: typeof AppFacturasNuevaRouteImport
      parentRoute: typeof AppFacturasRoute
    }
    '/_app/facturas/$facturaId/': {
      id: '/_app/facturas/$facturaId/'
      path: '/$facturaId'
      fullPath: '/facturas/$facturaId/'
      preLoaderRoute: typeof AppFacturasFacturaIdIndexRouteImport
      parentRoute: typeof AppFacturasRoute
    }
    '/_app/facturas/$facturaId/modificar': {
      id: '/_app/facturas/$facturaId/modificar'
      path: '/$facturaId/modificar'
      fullPath: '/facturas/$facturaId/modificar'
      preLoaderRoute: typeof AppFacturasFacturaIdModificarRouteImport
      parentRoute: typeof AppFacturasRoute
    }
    '/_app/facturas/borradores/$borradorId': {
      id: '/_app/facturas/borradores/$borradorId'
      path: '/borradores/$borradorId'
      fullPath: '/facturas/borradores/$borradorId'
      preLoaderRoute: typeof AppFacturasBorradoresBorradorIdRouteImport
      parentRoute: typeof AppFacturasRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppClientesNuevoRoute: typeof AppClientesNuevoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppClientesNuevoRoute: AppClientesNuevoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppConfiguracionRouteChildren {
  AppConfiguracionAuditoriaRoute: typeof AppConfiguracionAuditoriaRoute
  AppConfiguracionFacturacionRoute: typeof AppConfiguracionFacturacionRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
}

const AppConfiguracionRouteChildren: AppConfiguracionRouteChildren = {
  AppConfiguracionAuditoriaRoute: AppConfiguracionAuditoriaRoute,
  AppConfiguracionFacturacionRoute: AppConfiguracionFacturacionRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
}

const AppConfiguracionRouteWithChildren =
  AppConfiguracionRoute._addFileChildren(AppConfiguracionRouteChildren)

interface AppFacturasRouteChildren {
  AppFacturasNuevaRoute: typeof AppFacturasNuevaRoute
  AppFacturasFacturaIdModificarRoute: typeof AppFacturasFacturaIdModificarRoute
  AppFacturasBorradoresBorradorIdRoute: typeof AppFacturasBorradoresBorradorIdRoute
  AppFacturasFacturaIdIndexRoute: typeof AppFacturasFacturaIdIndexRoute
}

const AppFacturasRouteChildren: AppFacturasRouteChildren = {
  AppFacturasNuevaRoute: AppFacturasNuevaRoute,
  AppFacturasFacturaIdModificarRoute: AppFacturasFacturaIdModificarRoute,
  AppFacturasBorradoresBorradorIdRoute: AppFacturasBorradoresBorradorIdRoute,
  AppFacturasFacturaIdIndexRoute: AppFacturasFacturaIdIndexRoute,
}

const AppFacturasRouteWithChildren = AppFacturasRoute._addFileChildren(
  AppFacturasRouteChildren,
)

interface AppRouteChildren {
  AppAccesoDenegadoRoute: typeof AppAccesoDenegadoRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracionRoute: typeof AppConfiguracionRouteWithChildren
  AppCuentaRoute: typeof AppCuentaRoute
  AppFacturasRoute: typeof AppFacturasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccesoDenegadoRoute: AppAccesoDenegadoRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracionRoute: AppConfiguracionRouteWithChildren,
  AppCuentaRoute: AppCuentaRoute,
  AppFacturasRoute: AppFacturasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccesoRoute: AccesoRoute,
  CambiarContrasenaRoute: CambiarContrasenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
