/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as CambiarContrasenaRouteImport } from './routes/cambiar-contrasena'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccesoDenegadoRouteImport } from './routes/_app/acceso-denegado'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppCuentaRouteImport } from './routes/_app/cuenta'
import { Route as AppClientesClienteIdRouteImport } from './routes/_app/clientes/$clienteId'
import { Route as AppClientesNuevoRouteImport } from './routes/_app/clientes/nuevo'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app/configuracion/index'
import { Route as AppConfiguracionAuditoriaRouteImport } from './routes/_app/configuracion/auditoria'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app/configuracion/usuarios'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarContrasenaRoute = CambiarContrasenaRouteImport.update({
  id: '/cambiar-contrasena',
  path: '/cambiar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccesoDenegadoRoute = AppAccesoDenegadoRouteImport.update({
  id: '/acceso-denegado',
  path: '/acceso-denegado',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesNuevoRoute = AppClientesNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppConfiguracionAuditoriaRoute =
  AppConfiguracionAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracion': typeof AppConfiguracionRouteWithChildren
  '/cuenta': typeof AppCuentaRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
}
export interface FileRoutesByTo {
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/cuenta': typeof AppCuentaRoute
  '/': typeof AppIndexRoute
  '/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/clientes/nuevo': typeof AppClientesNuevoRoute
  '/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/_app/acceso-denegado': typeof AppAccesoDenegadoRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/_app/cuenta': typeof AppCuentaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/_app/clientes/nuevo': typeof AppClientesNuevoRoute
  '/_app/configuracion/auditoria': typeof AppConfiguracionAuditoriaRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/cambiar-contrasena'
    | '/acceso-denegado'
    | '/clientes'
    | '/configuracion'
    | '/cuenta'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/configuracion/auditoria'
    | '/configuracion/usuarios'
    | '/configuracion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acceso'
    | '/cambiar-contrasena'
    | '/acceso-denegado'
    | '/clientes'
    | '/cuenta'
    | '/'
    | '/clientes/$clienteId'
    | '/clientes/nuevo'
    | '/configuracion/auditoria'
    | '/configuracion/usuarios'
    | '/configuracion'
  id:
    | '__root__'
    | '/_app'
    | '/acceso'
    | '/cambiar-contrasena'
    | '/_app/acceso-denegado'
    | '/_app/clientes'
    | '/_app/configuracion'
    | '/_app/cuenta'
    | '/_app/'
    | '/_app/clientes/$clienteId'
    | '/_app/clientes/nuevo'
    | '/_app/configuracion/auditoria'
    | '/_app/configuracion/usuarios'
    | '/_app/configuracion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  CambiarContrasenaRoute: typeof CambiarContrasenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-contrasena': {
      id: '/cambiar-contrasena'
      path: '/cambiar-contrasena'
      fullPath: '/cambiar-contrasena'
      preLoaderRoute: typeof CambiarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acceso-denegado': {
      id: '/_app/acceso-denegado'
      path: '/acceso-denegado'
      fullPath: '/acceso-denegado'
      preLoaderRoute: typeof AppAccesoDenegadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuenta': {
      id: '/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$clienteId': {
      id: '/_app/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/nuevo': {
      id: '/_app/clientes/nuevo'
      path: '/nuevo'
      fullPath: '/clientes/nuevo'
      preLoaderRoute: typeof AppClientesNuevoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/auditoria': {
      id: '/_app/configuracion/auditoria'
      path: '/auditoria'
      fullPath: '/configuracion/auditoria'
      preLoaderRoute: typeof AppConfiguracionAuditoriaRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppClientesNuevoRoute: typeof AppClientesNuevoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppClientesNuevoRoute: AppClientesNuevoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppConfiguracionRouteChildren {
  AppConfiguracionAuditoriaRoute: typeof AppConfiguracionAuditoriaRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
}

const AppConfiguracionRouteChildren: AppConfiguracionRouteChildren = {
  AppConfiguracionAuditoriaRoute: AppConfiguracionAuditoriaRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
}

const AppConfiguracionRouteWithChildren =
  AppConfiguracionRoute._addFileChildren(AppConfiguracionRouteChildren)

interface AppRouteChildren {
  AppAccesoDenegadoRoute: typeof AppAccesoDenegadoRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracionRoute: typeof AppConfiguracionRouteWithChildren
  AppCuentaRoute: typeof AppCuentaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccesoDenegadoRoute: AppAccesoDenegadoRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracionRoute: AppConfiguracionRouteWithChildren,
  AppCuentaRoute: AppCuentaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccesoRoute: AccesoRoute,
  CambiarContrasenaRoute: CambiarContrasenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
