/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion Actual */
        get: operations["sesion_actual_api_v1_sesion_get"];
        put?: never;
        /** Iniciar Sesion */
        post: operations["iniciar_sesion_api_v1_sesion_post"];
        /** Cerrar Sesion */
        delete: operations["cerrar_sesion_api_v1_sesion_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cuenta/contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Contrasena */
        put: operations["cambiar_contrasena_api_v1_cuenta_contrasena_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Catalogos */
        get: operations["obtener_catalogos_api_v1_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Cliente */
        post: operations["crear_cliente_api_v1_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Cliente */
        get: operations["obtener_cliente_api_v1_clientes__cliente_id__get"];
        /** Editar Cliente */
        put: operations["editar_cliente_api_v1_clientes__cliente_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CambioContrasenaEntrada */
        CambioContrasenaEntrada: {
            /** Contrasena Actual */
            contrasena_actual: string;
            /** Contrasena Nueva */
            contrasena_nueva: string;
        };
        /** CatalogosSalida */
        CatalogosSalida: {
            /** Provincias */
            provincias: components["schemas"]["ProvinciaSalida"][];
            /** Paises */
            paises: string[];
            /** Paises Nif Iva */
            paises_nif_iva: string[];
            /** Tipos Identificacion */
            tipos_identificacion: components["schemas"]["TipoIdentificacionSalida"][];
        };
        /** ClienteEdicionEntrada */
        ClienteEdicionEntrada: {
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /**
             * Identificacion Pais
             * @default ES
             */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Direccion */
            direccion?: string | null;
            /** Codigo Postal */
            codigo_postal?: string | null;
            /** Localidad */
            localidad?: string | null;
            /** Provincia Codigo */
            provincia_codigo?: string | null;
            /** Provincia Texto */
            provincia_texto?: string | null;
            /**
             * Pais Residencia
             * @default ES
             */
            pais_residencia: string;
            /** Telefono */
            telefono?: string | null;
            /** Correo */
            correo?: string | null;
            /** Observaciones */
            observaciones?: string | null;
            /** Version */
            version: number;
        };
        /** ClienteEntrada */
        ClienteEntrada: {
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /**
             * Identificacion Pais
             * @default ES
             */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Direccion */
            direccion?: string | null;
            /** Codigo Postal */
            codigo_postal?: string | null;
            /** Localidad */
            localidad?: string | null;
            /** Provincia Codigo */
            provincia_codigo?: string | null;
            /** Provincia Texto */
            provincia_texto?: string | null;
            /**
             * Pais Residencia
             * @default ES
             */
            pais_residencia: string;
            /** Telefono */
            telefono?: string | null;
            /** Correo */
            correo?: string | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** ClienteSalida */
        ClienteSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /** Identificacion Pais */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Localidad */
            localidad: string | null;
            /** Provincia Nombre */
            provincia_nombre: string | null;
            /** Telefono */
            telefono: string | null;
            /** Correo */
            correo: string | null;
            /** Activo */
            activo: boolean;
            /** Direccion */
            direccion: string | null;
            /** Codigo Postal */
            codigo_postal: string | null;
            /** Provincia Codigo */
            provincia_codigo: string | null;
            /** Provincia Texto */
            provincia_texto: string | null;
            /** Pais Residencia */
            pais_residencia: string;
            /** Observaciones */
            observaciones: string | null;
            /** Version */
            version: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            creado_por: components["schemas"]["UsuarioReferencia"];
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            actualizado_por: components["schemas"]["UsuarioReferencia"];
        };
        /** CredencialesEntrada */
        CredencialesEntrada: {
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Contrasena */
            contrasena: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProvinciaSalida */
        ProvinciaSalida: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Nombre Visible */
            nombre_visible: string;
        };
        /**
         * Rol
         * @enum {string}
         */
        Rol: "administrador" | "empleado";
        /** SaludSalida */
        SaludSalida: {
            /**
             * Estado
             * @constant
             */
            estado: "ok";
        };
        /** SesionSalida */
        SesionSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expira En
             * Format: date-time
             */
            expira_en: string;
            /** Inactividad Segundos */
            inactividad_segundos: number;
        };
        /**
         * TipoCliente
         * @enum {string}
         */
        TipoCliente: "particular" | "empresa";
        /**
         * TipoIdentificacion
         * @description `NIF` o clave de la lista L7 de DsRegistroVeriFactu.xlsx v1.0 (spec F-2).
         *
         *     El 07 ("No censado") no se guarda en la ficha: se decide al generar el registro de
         *     facturación (research R-20.1).
         * @enum {string}
         */
        TipoIdentificacion: "NIF" | "02" | "03" | "04" | "05" | "06";
        /** TipoIdentificacionSalida */
        TipoIdentificacionSalida: {
            codigo: components["schemas"]["TipoIdentificacion"];
            /** Descripcion */
            descripcion: string;
            /** Ambito */
            ambito: string;
        };
        /** UsuarioReferencia */
        UsuarioReferencia: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Nombre */
            nombre: string;
            rol: components["schemas"]["Rol"];
            /** Activo */
            activo: boolean;
            /** Contrasena Temporal */
            contrasena_temporal: boolean;
            /** Bloqueado */
            bloqueado: boolean;
            /** Ultimo Acceso En */
            ultimo_acceso_en: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludSalida"];
                };
            };
        };
    };
    sesion_actual_api_v1_sesion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
        };
    };
    iniciar_sesion_api_v1_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_sesion_api_v1_sesion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cambiar_contrasena_api_v1_cuenta_contrasena_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioContrasenaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_catalogos_api_v1_catalogos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogosSalida"];
                };
            };
        };
    };
    crear_cliente_api_v1_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_cliente_api_v1_clientes__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_cliente_api_v1_clientes__cliente_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEdicionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
