/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion Actual */
        get: operations["sesion_actual_api_v1_sesion_get"];
        put?: never;
        /** Iniciar Sesion */
        post: operations["iniciar_sesion_api_v1_sesion_post"];
        /** Cerrar Sesion */
        delete: operations["cerrar_sesion_api_v1_sesion_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cuenta/contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Contrasena */
        put: operations["cambiar_contrasena_api_v1_cuenta_contrasena_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CambioContrasenaEntrada */
        CambioContrasenaEntrada: {
            /** Contrasena Actual */
            contrasena_actual: string;
            /** Contrasena Nueva */
            contrasena_nueva: string;
        };
        /** CredencialesEntrada */
        CredencialesEntrada: {
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Contrasena */
            contrasena: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Rol
         * @enum {string}
         */
        Rol: "administrador" | "empleado";
        /** SaludSalida */
        SaludSalida: {
            /**
             * Estado
             * @constant
             */
            estado: "ok";
        };
        /** SesionSalida */
        SesionSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expira En
             * Format: date-time
             */
            expira_en: string;
            /** Inactividad Segundos */
            inactividad_segundos: number;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Nombre */
            nombre: string;
            rol: components["schemas"]["Rol"];
            /** Activo */
            activo: boolean;
            /** Contrasena Temporal */
            contrasena_temporal: boolean;
            /** Bloqueado */
            bloqueado: boolean;
            /** Ultimo Acceso En */
            ultimo_acceso_en: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludSalida"];
                };
            };
        };
    };
    sesion_actual_api_v1_sesion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
        };
    };
    iniciar_sesion_api_v1_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_sesion_api_v1_sesion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cambiar_contrasena_api_v1_cuenta_contrasena_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioContrasenaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
