/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion Actual */
        get: operations["sesion_actual_api_v1_sesion_get"];
        put?: never;
        /** Iniciar Sesion */
        post: operations["iniciar_sesion_api_v1_sesion_post"];
        /** Cerrar Sesion */
        delete: operations["cerrar_sesion_api_v1_sesion_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cuenta/contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Contrasena */
        put: operations["cambiar_contrasena_api_v1_cuenta_contrasena_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Catalogos */
        get: operations["obtener_catalogos_api_v1_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Clientes */
        get: operations["listar_clientes_api_v1_clientes_get"];
        put?: never;
        /** Crear Cliente */
        post: operations["crear_cliente_api_v1_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/indicadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Indicadores */
        get: operations["obtener_indicadores_api_v1_clientes_indicadores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Cliente */
        get: operations["obtener_cliente_api_v1_clientes__cliente_id__get"];
        /** Editar Cliente */
        put: operations["editar_cliente_api_v1_clientes__cliente_id__put"];
        post?: never;
        /** Borrar Cliente */
        delete: operations["borrar_cliente_api_v1_clientes__cliente_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/desactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desactivar Cliente */
        post: operations["desactivar_cliente_api_v1_clientes__cliente_id__desactivacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/reactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivar Cliente */
        post: operations["reactivar_cliente_api_v1_clientes__cliente_id__reactivacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Sin los eliminados, salvo `incluir_eliminados` (filtro de la auditoría; FR-061).
         */
        get: operations["listar_usuarios_api_v1_usuarios_get"];
        put?: never;
        /** Crear Usuario */
        post: operations["crear_usuario_api_v1_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Usuario */
        get: operations["obtener_usuario_api_v1_usuarios__usuario_id__get"];
        put?: never;
        post?: never;
        /**
         * Eliminar Usuario
         * @description Elimina un usuario desactivado; lo que registró se conserva (FR-061).
         */
        delete: operations["eliminar_usuario_api_v1_usuarios__usuario_id__delete"];
        options?: never;
        head?: never;
        /** Editar Usuario */
        patch: operations["editar_usuario_api_v1_usuarios__usuario_id__patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/desactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desactivar Usuario */
        post: operations["desactivar_usuario_api_v1_usuarios__usuario_id__desactivacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/reactivacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivar Usuario */
        post: operations["reactivar_usuario_api_v1_usuarios__usuario_id__reactivacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/restablecimiento-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablecer Contrasena */
        post: operations["restablecer_contrasena_api_v1_usuarios__usuario_id__restablecimiento_contrasena_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Auditoria */
        get: operations["consultar_auditoria_api_v1_auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CambioContrasenaEntrada */
        CambioContrasenaEntrada: {
            /** Contrasena Actual */
            contrasena_actual: string;
            /** Contrasena Nueva */
            contrasena_nueva: string;
        };
        /** CatalogosSalida */
        CatalogosSalida: {
            /** Provincias */
            provincias: components["schemas"]["ProvinciaSalida"][];
            /** Paises */
            paises: string[];
            /** Paises Nif Iva */
            paises_nif_iva: string[];
            /** Tipos Identificacion */
            tipos_identificacion: components["schemas"]["TipoIdentificacionSalida"][];
        };
        /** ClienteEdicionEntrada */
        ClienteEdicionEntrada: {
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /**
             * Identificacion Pais
             * @default ES
             */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Direccion */
            direccion?: string | null;
            /** Codigo Postal */
            codigo_postal?: string | null;
            /** Localidad */
            localidad?: string | null;
            /** Provincia Codigo */
            provincia_codigo?: string | null;
            /** Provincia Texto */
            provincia_texto?: string | null;
            /**
             * Pais Residencia
             * @default ES
             */
            pais_residencia: string;
            /** Telefono */
            telefono?: string | null;
            /** Correo */
            correo?: string | null;
            /** Observaciones */
            observaciones?: string | null;
            /** Version */
            version: number;
        };
        /** ClienteEntrada */
        ClienteEntrada: {
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /**
             * Identificacion Pais
             * @default ES
             */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Direccion */
            direccion?: string | null;
            /** Codigo Postal */
            codigo_postal?: string | null;
            /** Localidad */
            localidad?: string | null;
            /** Provincia Codigo */
            provincia_codigo?: string | null;
            /** Provincia Texto */
            provincia_texto?: string | null;
            /**
             * Pais Residencia
             * @default ES
             */
            pais_residencia: string;
            /** Telefono */
            telefono?: string | null;
            /** Correo */
            correo?: string | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** ClienteResumenSalida */
        ClienteResumenSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /** Identificacion Pais */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Localidad */
            localidad: string | null;
            /** Provincia Nombre */
            provincia_nombre: string | null;
            /** Telefono */
            telefono: string | null;
            /** Correo */
            correo: string | null;
            /** Activo */
            activo: boolean;
        };
        /** ClienteSalida */
        ClienteSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            tipo: components["schemas"]["TipoCliente"];
            /** Nombre */
            nombre: string;
            /** Identificacion Pais */
            identificacion_pais: string;
            identificacion_tipo: components["schemas"]["TipoIdentificacion"];
            /** Identificacion Numero */
            identificacion_numero: string;
            /** Localidad */
            localidad: string | null;
            /** Provincia Nombre */
            provincia_nombre: string | null;
            /** Telefono */
            telefono: string | null;
            /** Correo */
            correo: string | null;
            /** Activo */
            activo: boolean;
            /** Direccion */
            direccion: string | null;
            /** Codigo Postal */
            codigo_postal: string | null;
            /** Provincia Codigo */
            provincia_codigo: string | null;
            /** Provincia Texto */
            provincia_texto: string | null;
            /** Pais Residencia */
            pais_residencia: string;
            /** Observaciones */
            observaciones: string | null;
            /** Version */
            version: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            creado_por: components["schemas"]["UsuarioReferencia"];
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            actualizado_por: components["schemas"]["UsuarioReferencia"];
        };
        /** CredencialesEntrada */
        CredencialesEntrada: {
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Contrasena */
            contrasena: string;
        };
        /** EventoSalida */
        EventoSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ocurrido En
             * Format: date-time
             */
            ocurrido_en: string;
            tipo: components["schemas"]["TipoEvento"];
            actor: components["schemas"]["UsuarioReferencia"] | null;
            /** Actor Nombre Usuario */
            actor_nombre_usuario: string | null;
            /** Origen Ip */
            origen_ip: string | null;
            /** Agente */
            agente: string | null;
            usuario_afectado: components["schemas"]["UsuarioReferencia"] | null;
            /** Cliente Id */
            cliente_id: string | null;
            /** Detalle */
            detalle: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicadoresSalida */
        IndicadoresSalida: {
            /** Activos */
            activos: number;
            /** Nuevos Este Anio */
            nuevos_este_anio: number;
        };
        /** Pagina[ClienteResumenSalida] */
        Pagina_ClienteResumenSalida_: {
            /** Elementos */
            elementos: components["schemas"]["ClienteResumenSalida"][];
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Tamano */
            tamano: number;
        };
        /** Pagina[EventoSalida] */
        Pagina_EventoSalida_: {
            /** Elementos */
            elementos: components["schemas"]["EventoSalida"][];
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Tamano */
            tamano: number;
        };
        /** ProvinciaSalida */
        ProvinciaSalida: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Nombre Visible */
            nombre_visible: string;
        };
        /**
         * Rol
         * @enum {string}
         */
        Rol: "administrador" | "empleado";
        /** SaludSalida */
        SaludSalida: {
            /**
             * Estado
             * @constant
             */
            estado: "ok";
        };
        /** SesionSalida */
        SesionSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expira En
             * Format: date-time
             */
            expira_en: string;
            /** Inactividad Segundos */
            inactividad_segundos: number;
        };
        /**
         * TipoCliente
         * @enum {string}
         */
        TipoCliente: "particular" | "empresa";
        /**
         * TipoEvento
         * @enum {string}
         */
        TipoEvento: "acceso_correcto" | "acceso_fallido" | "acceso_bloqueado" | "acceso_limitado" | "cierre_sesion" | "contrasena_cambiada" | "contrasena_restablecida" | "usuario_creado" | "usuario_rol_cambiado" | "usuario_desactivado" | "usuario_reactivado" | "usuario_eliminado" | "cliente_creado" | "cliente_editado" | "cliente_desactivado" | "cliente_reactivado" | "cliente_borrado";
        /**
         * TipoIdentificacion
         * @description `NIF` o clave de la lista L7 de DsRegistroVeriFactu.xlsx v1.0 (spec F-2).
         *
         *     El 07 ("No censado") no se guarda en la ficha: se decide al generar el registro de
         *     facturación (research R-20.1).
         * @enum {string}
         */
        TipoIdentificacion: "NIF" | "02" | "03" | "04" | "05" | "06";
        /** TipoIdentificacionSalida */
        TipoIdentificacionSalida: {
            codigo: components["schemas"]["TipoIdentificacion"];
            /** Descripcion */
            descripcion: string;
            /** Ambito */
            ambito: string;
        };
        /** UsuarioAltaEntrada */
        UsuarioAltaEntrada: {
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Nombre */
            nombre: string;
            rol: components["schemas"]["Rol"];
        };
        /** UsuarioConContrasenaTemporalSalida */
        UsuarioConContrasenaTemporalSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /** Contrasena Temporal */
            contrasena_temporal: string;
        };
        /** UsuarioEdicionEntrada */
        UsuarioEdicionEntrada: {
            /** Nombre */
            nombre?: string | null;
            rol?: components["schemas"]["Rol"] | null;
        };
        /** UsuarioReferencia */
        UsuarioReferencia: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Eliminado */
            eliminado: boolean;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Usuario */
            nombre_usuario: string;
            /** Nombre */
            nombre: string;
            rol: components["schemas"]["Rol"];
            /** Activo */
            activo: boolean;
            /** Eliminado */
            eliminado: boolean;
            /** Contrasena Temporal */
            contrasena_temporal: boolean;
            /** Bloqueado */
            bloqueado: boolean;
            /** Ultimo Acceso En */
            ultimo_acceso_en: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludSalida"];
                };
            };
        };
    };
    sesion_actual_api_v1_sesion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
        };
    };
    iniciar_sesion_api_v1_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_sesion_api_v1_sesion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cambiar_contrasena_api_v1_cuenta_contrasena_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioContrasenaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_catalogos_api_v1_catalogos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogosSalida"];
                };
            };
        };
    };
    listar_clientes_api_v1_clientes_get: {
        parameters: {
            query?: {
                q?: string | null;
                provincia?: string | null;
                tipo?: components["schemas"]["TipoCliente"] | null;
                estado?: "activos" | "inactivos" | "todos";
                orden?: "nombre_asc" | "nombre_desc" | "recientes" | "antiguos";
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ClienteResumenSalida_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_cliente_api_v1_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_indicadores_api_v1_clientes_indicadores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicadoresSalida"];
                };
            };
        };
    };
    obtener_cliente_api_v1_clientes__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_cliente_api_v1_clientes__cliente_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEdicionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    borrar_cliente_api_v1_clientes__cliente_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_cliente_api_v1_clientes__cliente_id__desactivacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivar_cliente_api_v1_clientes__cliente_id__reactivacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_usuarios_get: {
        parameters: {
            query?: {
                incluir_eliminados?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_api_v1_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioAltaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioConContrasenaTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_usuario_api_v1_usuarios__usuario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_usuario_api_v1_usuarios__usuario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_usuario_api_v1_usuarios__usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioEdicionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_usuario_api_v1_usuarios__usuario_id__desactivacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivar_usuario_api_v1_usuarios__usuario_id__reactivacion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_contrasena_api_v1_usuarios__usuario_id__restablecimiento_contrasena_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioConContrasenaTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_auditoria_api_v1_auditoria_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
                usuario_id?: string | null;
                tipo?: components["schemas"]["TipoEvento"] | null;
                cliente_id?: string | null;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_EventoSalida_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
