import type { TipoEvento } from '../../api/tipos'

/** Nombre en español de cada tipo de evento de auditoría. */
export const TIPOS_EVENTO: Record<TipoEvento, string> = {
  acceso_correcto: 'Acceso correcto',
  acceso_fallido: 'Acceso fallido',
  acceso_bloqueado: 'Cuenta bloqueada',
  acceso_limitado: 'Acceso limitado por origen',
  cierre_sesion: 'Cierre de sesión',
  contrasena_cambiada: 'Contraseña cambiada',
  contrasena_restablecida: 'Contraseña restablecida',
  usuario_creado: 'Usuario creado',
  usuario_rol_cambiado: 'Rol cambiado',
  usuario_desactivado: 'Usuario desactivado',
  usuario_reactivado: 'Usuario reactivado',
  usuario_eliminado: 'Usuario eliminado',
  cliente_creado: 'Cliente creado',
  cliente_editado: 'Cliente editado',
  cliente_desactivado: 'Cliente desactivado',
  cliente_reactivado: 'Cliente reactivado',
  cliente_borrado: 'Cliente borrado',
  borrador_factura_creado: 'Borrador de factura creado',
  borrador_factura_editado: 'Borrador de factura editado',
  borrador_factura_eliminado: 'Borrador de factura eliminado',
  factura_emitida: 'Factura emitida',
  factura_anulada: 'Factura anulada',
  factura_rectificada: 'Factura rectificada',
  configuracion_facturacion_cambiada: 'Configuración de facturación cambiada',
  contador_ajustado: 'Numeración ajustada',
  cadena_verificada: 'Registro de facturación comprobado',
  cadena_inconsistente: 'Registro de facturación inconsistente',
  borrador_presupuesto_creado: 'Borrador de presupuesto creado',
  borrador_presupuesto_editado: 'Borrador de presupuesto editado',
  borrador_presupuesto_eliminado: 'Borrador de presupuesto eliminado',
  presupuesto_emitido: 'Presupuesto emitido',
  presupuesto_modificado: 'Presupuesto modificado',
  presupuesto_anulado: 'Presupuesto anulado',
  presupuesto_convertido: 'Presupuesto convertido en factura',
}
